### ISSUE TITLE
Demo please?

### ISSUE THREAD

**Issue by undercloud** [svelto/svelto#1]

**Comment by fabiospampinato** [comment]
I still have to write a proper readme and the website as well, but in the mean time if you wish you can do the following to run the demo:

- make sure you have (Meteor)[https://www.meteor.com/install] installed
- download the repo
- `cd svelto`
- `npm install`
- `gulp build --env=development`
- `cd demo`
- `meteor run`

**Comment by undercloud** [comment]
)))
